### PR TITLE
Add Unsafe version of XHFPModelVertexBufferWriter

### PR DESCRIPTION
**Pull request by IMS212**
This PR targets 1.16 instead of 1.17, as we can merge into 1.17 later. 

This supersedes #19.

### CODE REVIEW

**Comment by IMS212** [comment]
This should be ready to merge, however as per your earlier comments about code deduplication I'll keep this as a draft for now.

**Comment by coderbot16** [comment]
Closing this since the Sodium fork will be getting deprecated in the near future.

**Comment by IMS212** [comment]
Would it be fine to reopen this under the iris sodium compatibility branch? This improves performance quite a bit

**Comment by coderbot16** [comment]
For now I'm going to leave this, but I created https://github.com/IrisShaders/Iris/issues/982 as a reminder to come back to it sometime in the future.

**Pull request closed without merging**
